---
- name: Install Apache web server
  hosts: all
  become: yes
  tasks:
    - name: Install apache2 package
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure apache2 service is started and enabled
      systemd:
        name: apache2
        state: started
        enabled: yes
