--- 
- hosts: all
  #ignore_unreachable: true
  tasks: 
    - name: list_files
      shell: ls
      ignore_errors: yes
      register: list_values
    - debug: 
        var: list_values.stdout_lines

    - name: display_date
      shell: date
      register: today_date
    - debug:
        var: today_date.stdout_lines

